spring:
  mvc:
    static-path-pattern: /swagger*
  profiles:
    active: dev

#server:
#  servlet:
#    context-path: /api/v1/

springdoc:
  swagger:
    ui:
      path: /swagger-ui.html

logging:
  level:
    root: info
